[package]
name = "reverse_sh"
version = "0.1.0"
authors = ["lgraham076 <langstongraham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
